# Generated by Django 3.1.12 on 2021-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210717_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stoploss',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='trade',
            name='target',
            field=models.FloatField(default=10),
        ),
    ]
